# Constans, function names, etc for auto completion tasks
PYCONSOLE_CONSTANTS = ["bye", "connect", "help", "loop", "test", "verbose"]
KEYKIT_FUNCTIONS = [
    "abs", "acos", "add2tooltypes", "addbootfunc", "addpostrc", "addprerc",
    "addrecorded", "addrootevery", "allchords", "alloff", "allscales",
    "allsusoff", "alpha_back", "alphafun", "ano", "anoall", "apply",
    "applyfunc", "applynear", "areacontains", "argv", "argvlist", "arpeggio",
    "arraycopy", "arraylist", "arrayprint", "arraysort", "arraysortonindex",
    "ascii", "asin", "atan", "attime", "attribarray", "autopan", "bankselect",
    "bd_round", "beatinfo", "bitmap", "bits2phrase", "bootvars", "bpm",
    "broadcastcontrol", "broadcastprogram", "browsefiles", "browsephrase",
    "browsesyx", "canonic", "chadjust", "chan", "chancolortestphrase",
    "chanexpressionchange", "changeprogchange", "chaninfo", "CHANPRESSURE",
    "chansplit", "chanvolchange", "char2bits", "chdir", "chfilter", "chord",
    "chordmel", "chordnamed", "CLOCK", "close", "closemidi", "closenkill",
    "closest", "closestmap", "closestt", "cmd_addroot", "cmd_adjvol",
    "cmd_applynear", "cmd_applyseq", "cmd_arpeggio", "cmd_autopan",
    "cmd_average", "cmd_bs", "cmd_chordize", "cmd_crescendo", "cmd_debank",
    "cmd_decrescendo", "cmd_dedup", "cmd_dedupdur", "cmd_durscale", "cmd_echo",
    "cmd_eventime", "cmd_evolve", "cmd_expandvol", "cmd_fade", "cmd_flip",
    "cmd_fractal", "cmd_inverti", "cmd_invertidir", "cmd_leavechan",
    "cmd_leavedur", "cmd_leavenearbeat", "cmd_leaventh", "cmd_leaveonbeat",
    "cmd_leaverand", "cmd_leavetype", "cmd_leavevol", "cmd_legato", "cmd_mono",
    "cmd_noise", "cmd_null", "cmd_ornament", "cmd_permute", "cmd_preecho",
    "cmd_quantize", "cmd_quantizedur", "cmd_quantizefirst", "cmd_removechan",
    "cmd_removedur", "cmd_removenearbeat", "cmd_removenth", "cmd_removeonbeat",
    "cmd_removerand", "cmd_removetype", "cmd_removevol", "cmd_repeat",
    "cmd_repeatquant", "cmd_replace", "cmd_reverse", "cmd_scadjust",
    "cmd_scafilt", "cmd_scalast", "cmd_setchan", "cmd_setduration",
    "cmd_shift", "cmd_shuffle", "cmd_slowdown", "cmd_spread", "cmd_step",
    "cmd_stutter", "cmd_stutterrand", "cmd_swapnotes", "cmd_thin",
    "cmd_thincontrol", "cmd_timescale", "cmd_tonerow", "cmd_transpose",
    "cmd_transposeseq", "cmd_volscale", "collectsysexdump", "color",
    "Colorfunc", "colormix", "completescale", "consloop", "consoleprintf",
    "consoutloop", "constant", "continuemsg", "controller", "CONTROLLER",
    "controllerlist", "controllernotes", "coreleft", "cos", "crescendo",
    "currtime", "cut", "CUT_CHANNEL", "CUT_FLAGS", "CUT_NOTTYPE", "CUT_TIME",
    "CUT_TYPE", "datamsg", "debank", "debug", "debugfile", "decpriority",
    "dedup", "dedupdur", "definecontrol", "definelocks", "defineprogram",
    "delay", "delete", "deletemidiin", "deleteobject", "derest", "docmd",
    "dodemo", "dokeylocal", "domethod", "dprint", "draw_downarrow",
    "draw_uparrow", "drawx", "dupsof", "dur", "echo", "echomaster",
    "efunction", "error", "Errorfunc", "eval_number", "evalstring",
    "eventime", "evolve", "exit", "Exitfunc", "exp", "expandvol",
    "expressionnotes", "fakebrowsefiles", "fakekeyboardinput", "fib",
    "fifoctl", "fifosize", "filecat", "fileexists", "fileisreadable",
    "filetime", "filetopitches", "fileWatch", "fillspace", "findroot",
    "findtask", "finishoff", "firsthalf", "fit2root", "flip", "float", "floor",
    "flush", "focus", "fractal", "fullinfo", "fulltrace", "funkey", "fxy",
    "garbcollect", "gauss", "gcd", "gcd2", "generateclock", "get", "getanote",
    "getastr", "getsysexdump", "gettid", "gexpressionchange", "globalvalue",
    "gmastervol", "gmresetall", "grabmouse", "grabmousefifo", "gs_chksum",
    "gs_coarsetune", "gs_finetune", "gs_mastertune", "gs_mfxpara",
    "gs_mfxpart", "gs_mfxtype", "gs_nrpnattack", "gs_nrpncombi",
    "gs_nrpnctrl", "gs_nrpncutoff", "gs_nrpndecay", "gs_nrpnrelease",
    "gs_nrpnreso", "gs_nrpnvibrato", "gs_partmode", "gs_reset", "gs_scaletune",
    "gs_strangemap", "gs_toneselect", "gs_turnoff", "gs_turnon", "gvolchange",
    "haschannel", "head", "help", "highest", "highestnt", "http_client",
    "INCLUSIVE", "incpriority", "inherited", "inport", "integer", "interploop",
    "Intrfunc", "iserasechar", "isinarea", "isinscale", "isnearbeat",
    "isonbeat", "kerror", "keykithostname", "keyrc", "kill", "killtids",
    "konnectinterp", "kserver", "kvalbutton_mkmenu", "lastbunch",
    "lastnotechord", "latest", "launchpad_flash", "launchpad_init",
    "launchpad_off", "launchpad_on", "launchpad_realtime", "launchpad_reset",
    "launchrand", "layout_horizontal", "layout_vertical", "lcm", "legato",
    "length", "limitsof", "limitval", "linesout", "linux_listen", "linux_send",
    "listen", "listports", "lock", "log", "log10", "logit", "lookforandopen",
    "lookforport", "lookup", "loophack", "lowest", "lowestnt", "lsdir",
    "makeholdernote", "makenote", "makerootevery", "makescale", "mapport",
    "max", "maxvolume", "mdep", "mergeonly", "mergeonoff", "methodbroadcast",
    "methodforward2first", "midi", "midibytes", "MIDIBYTES", "midifile",
    "midiloop", "midirouter", "midirouter_cleanup", "milliclicks",
    "milliclock", "millisince", "millisleep", "min", "minduration",
    "minvolume", "MIXED", "modulationnotes", "mono", "mousedemo", "mousedo",
    "mouseforward", "mouseloop", "mouseplay", "mouseplaytask", "mousereadfile",
    "mouserec", "mousewarp", "mousewritefile", "m_top", "newpagename",
    "nextquant", "nexttime", "noise", "noiseval", "nonnotes", "NORMAL",
    "normboot", "normexit", "normintr", "normredraw", "normresize", "NOTE",
    "note2holder", "NOTEOFF", "NOTEON", "noticecontrollers", "noticeprogram",
    "Now", "nrpn", "nsimul", "nullfunc", "nullfunction", "numquant", "object",
    "objectinfo", "objectlist", "octavefence", "oldcontrolthin", "oldnargs",
    "oldtypeof", "oldxy", "oneovrf", "onerror", "onexit", "onlynotes", "open",
    "ornament", "oscgroup_listen", "oscgroup_send", "osc_listen", "osc_sean",
    "osc_send", "osc_sendto", "outport", "page_label", "page_new", "page_post",
    "page_readmerge", "page_readnew", "page_switch", "page_switchto",
    "page_write", "pannote", "pannotes", "patchchange", "pathescape",
    "pathsearch", "permutations", "permutations_visit", "phdump", "phrase",
    "picknote", "pickphr", "picnic", "picnic2", "picnicmedley", "picnic_reset",
    "pitch", "pitchbend", "PITCHBEND", "pitchbendnotes", "pitchlimit",
    "playchords", "playChordstask", "popup", "portsopened", "POSITION", "pow",
    "preecho", "prelocaldefaults", "PRESSURE", "prevquant", "print", "printf",
    "printit", "priority", "proc_list", "progchange", "progchangenotes",
    "PROGRAM", "prstack", "put", "quantize", "quantizedur", "quantizefirst",
    "querycontrol", "queryprogram", "rand", "randdur", "randpitch", "randvol",
    "rcdefaults", "rcdefaults_mdep", "rcpostboot", "readandsend", "readedit",
    "readedit2", "readeveryfile", "readfile", "readkey", "readmf",
    "readmfchan", "readmid", "readphr", "readraw", "readrawplay", "realexpr",
    "realexprtask", "realgmreset", "realmidi", "realmiditask", "realslow",
    "realtime", "reboot", "Rebootfunc", "recfilteron", "rectresize",
    "Redrawfunc", "refunc", "regicontrol", "regiprogram", "registop",
    "rekeylib", "relay", "relays", "relayscan", "remotecons",
    "remotecons_loop", "remotecons_task", "repeat", "repfade", "repleng",
    "rereadlib", "rereadlibs", "resetall", "Resizefunc", "restartconfig",
    "reverse", "revpitch", "Root", "rootmon", "round", "rpn_bendrange",
    "rpn_coarsetune", "rpn_finetune", "rpnmsg", "scadjust", "scadjust_last",
    "scadjustseqinplace", "scadur", "scafilt", "scale_aeolian",
    "scale_chromatic", "scale_dorian", "scale_fifths", "scale_harminor",
    "scale_ionian", "scale_last", "scale_locrian", "scale_lydian",
    "scale_melminor", "scale_mixolydian", "scalenamed", "scale_newage",
    "scaleng", "scale_phrygian", "scalevertical", "scatimes", "scavol",
    "screen", "scriptWatch", "secondhalf", "seconds", "sendNoteOffs",
    "setbendrange", "setdefaultchancolormap", "setdefaults", "setmouse",
    "setsnarf", "shuffle", "simulinfo", "sin", "sizeof", "sleeptill",
    "slidermon", "smtptest", "snapshot", "sock_client", "sock_server",
    "sock_test", "SONG", "split", "spliteven", "splitonstarts",
    "splitonstarts_orig", "spread", "sprintf", "sqrt", "startmsg",
    "STARTSTOPCONT", "status", "step", "step_16", "step_32", "step_8", "stop",
    "stopmsg", "strbits", "strindex", "string", "strip", "subbytes", "substr",
    "suffixof", "sussect", "sustainnotes", "swapnote", "sweeptool",
    "symbolnamed", "sync", "syncphr", "synctostart", "SYSEX", "system", "tail",
    "tan", "taskinfo", "task_launchrand", "task_loop", "task_midirouter",
    "task_monitor", "task_rootmon", "task_slidermon", "tempo", "temponote",
    "tension", "test1f", "test_connect", "testgauss", "testgenerateclock",
    "test_listen", "test_loop", "test_monitor", "testnoiseval", "testrand",
    "textfunc", "thincontrol", "thinit", "tick", "time", "togglemet",
    "tonerow", "tonerow_old", "toolize", "toolnotes", "tooltypes",
    "tooltypesall", "transform_arpeggio", "transform_fractal",
    "transform_none", "transform_null", "transform_preecho2",
    "transform_reverse", "transform_slow", "transform_spread",
    "transform_step", "transform_step2", "transform_stutter",
    "transform_thin", "transform_tonerow", "transpose", "transposeseqinplace",
    "transposeseqrepeat", "TRUNCATE", "txpatches", "txperfs", "type", "typeof",
    "udp_listen", "udp_listen2", "udp_test_send", "ungrabmouse",
    "ungrabmousefifo", "uniqnum", "unlock", "unregicontrol", "unregiprogram",
    "updatelib", "virusreq1", "virustest", "vol", "volmonitor", "volumenotes",
    "wait", "waitdown", "waitforstart", "waitncall", "waitneval",
    "waitnmethod", "waitnput", "waitnsweep", "waitup", "wbroadcast", "wcopy",
    "wdelete", "wdump", "wgenepool_mon", "wgrabbag_mon", "whelp",
    "windowobject", "winvis", "wmax", "wmove", "wpastetool", "wresize",
    "wrestore", "writemf", "writephr", "wselect", "wshowdump", "wsnarf",
    "wsnarftool", "wswap", "xymid", "xystr", "zoomoutandredraw",
]

KEYKIT_STATEMENTS = [
    "break",
    "continue",
    "define",
    "else",
    "finally",
    "for",
    "from",
    "function",
    "global",
    "if",
    "import",
    "in",
    "include",
    "is",
    "library",
    "method",
    "print",
    "raise",
    "readonly",
    "return",
    "task",
    "try",
    "undefine",
    "while",
]
